server {
    listen      8080;
    server_name localhost;

    client_max_body_size 2097152;

    location /cgi-bin/ {
        root            ./www;
        allowed_methods GET POST;
        cgi_pass        .py  /usr/bin/python3;
        cgi_pass        .sh  /bin/bash;
    }

    location /php/ {
        root            ./www;
        allowed_methods GET POST;
        cgi_pass        .php /usr/bin/php-cgi;
    }

    location / {
        root            ./www;
        index           index.html;
        allowed_methods GET;
    }
}
