server {
    listen      8080;
    server_name localhost;

    location / {
        root ./www/a;
        allowed_methods GET;
    }
}

server {
    listen      8080;
    server_name localhost;

    location / {
        root ./www/b;
        allowed_methods GET;
    }
}
