server {
    listen      8080;
    server_name  _ default;

	client_max_body_size 0;

    error_page 418 /teapot.html;

    location / {
        root            ./www;
        index           index.html;
        allowed_methods GET;
    }

    location /api {
        root            ./www;
        allowed_methods GET POST;
    }

    location /api/v1 {
        root            ./www;
        allowed_methods GET;
    }

    location /api/v1/admin {
        root            ./www;
        allowed_methods GET POST DELETE;
    }


    location /teapot.html {
        root            ./www;
        allowed_methods GET;
    }
}
