server {
    listen      8080;
    server_name localhost;

    location /old-blog {
        return 301 /blog;
    }

    location /external {
        return 302 https://www.example.org/;
    }

    location /api-old {
        return 307 /api/v2;
    }

    location /blog {
        root            ./www;
        index           index.html;
        allowed_methods GET;
    }

    location /api/v2 {
        root            ./www/api;
        allowed_methods GET POST;
    }

    location / {
        root            ./www;
        index           index.html;
        allowed_methods GET;
    }
}
