server {
    listen      8080;
    server_name site-a.local;

    location / {
        root            ./www/site-a;
        index           index.html;
        allowed_methods GET;
    }
}

server {
    listen      8080;
    server_name site-b.local www.site-b.local;

    location / {
        root            ./www/site-b;
        index           index.html;
        allowed_methods GET;
    }
}

server {
    listen      9090;
    server_name admin.local;

    client_max_body_size 5242880;

    location / {
        root            ./www/admin;
        index           dashboard.html;
        allowed_methods GET POST;
    }
}
